/*
  Copyright © 2025 Aakash Electronics. All Rights Reserved.
  Unauthorized copying or reproduction is strictly prohibited.
*/
window.STRINGS = {
  en: {
    util_open: "OPEN MON–SAT · 10:00–20:00",
    util_addr: "SP ROAD, BENGALURU",

    nav_about: "About",
    nav_contact: "Contact",
    nav_visit: "Visit Shop",

    hero_eyebrow: "EST. 1994 · BENGALURU",
    hero_h1: 'Electronic components for <em class="accent">industry</em>,<br>education, and curious minds.',
    hero_lede: "Aakash Electronics is a 30-year-old supply house on SP Road. From bulk industrial orders to hobby kits for students — we stock what makes things work.",
    hero_cta1: "Get in Touch",
    hero_cta2: "Our Story",
    hero_trust_label: "Trusted by",

    cat_label: "WHAT WE STOCK",
    cat_title_a: "Twelve categories, ",
    cat_title_em: "every component you need",
    cat_title_b: ".",
    cat_lede: "Transistors, ICs, capacitors, resistors, connectors, cables, sensors, dev boards, LEDs, PCBs, tools, and power adaptors — all at one counter on SP Road.",
    cat: {
      passive:     { name: "Resistors & Passives",   meta: "Carbon Film · Metal Film · Potentiometers · Inductors", count: "1,200+ SKUs" },
      transistors: { name: "Transistors",             meta: "BC · A/B/C/D/K/R series · 500+ part numbers",           count: "3,000+ SKUs" },
      ics:         { name: "ICs & Audio Modules",     meta: "TDA · LA · STK · AN · UM · UPC · TA series",            count: "1,800+ SKUs" },
      capacitors:  { name: "Capacitors",              meta: "Ceramic 2pF–330K · Electrolytic · Polyester",           count: "2,000+ SKUs" },
      connectors:  { name: "Connectors & Audio",      meta: "RCA · XLR · BNC · USB · HDMI · DIN · Banana",          count: "640+ SKUs"   },
      leds:        { name: "LEDs & Switches",         meta: "5mm · 3mm · Candy · Tact 6×6 · 12×12 · Rocker",        count: "280+ SKUs"   },
      wires:       { name: "Cables & Wires",          meta: "DC Wire · Patch Cords · HDMI · USB · Shielded",         count: "320+ SKUs"   },
      sensors:     { name: "Sensors & Modules",       meta: "PIR · Gas MQ2/5/135 · Temp · RFID · RF 433MHz",         count: "640+ SKUs"   },
      kits:        { name: "Dev Boards & Kits",       meta: "Arduino · 8051 · AVR · PIC · ESP32 · Raspberry Pi",    count: "180+ SKUs"   },
      pcbs:        { name: "PCBs & Prototyping",      meta: "Perfboards · Breadboards · Single/Double Side",         count: "210+ SKUs"   },
      tools:       { name: "Tools & Soldering",       meta: "Soldron Irons · Solder Wire · Pliers · Cutters",        count: "490+ SKUs"   },
      power:       { name: "Power & Adaptors",        meta: "SMPS · Laptop Adaptors · 5V–20V · Regulators",         count: "880+ SKUs"   }
    },

    bulk_eyebrow: "BULK & B2B",
    bulk_title: "Need a large order by the weekend?",
    bulk_p: "We supply manufacturing units, automation integrators, and government organisations across Karnataka. Contact our trade desk for quotations on bulk orders and BOM sourcing.",
    bulk_b1: "Volume pricing on bulk orders",
    bulk_b2: "GST invoicing · Cash, UPI & NEFT accepted",
    bulk_b3: "Serving L&T, BEL, Indian Railways and more",
    bulk_b4: "Wires & cables for infrastructure projects",
    bulk_cta: "Request a Quote",
    bulk_img: "BULK ORDER · B2B",

    student_eyebrow: "FOR STUDENTS & MAKERS",
    student_title: "Build something this weekend.",
    student_p: "Curated kits for first-year electronics, robotics clubs, and hobbyists. Our radio assembly kits have been top sellers among engineering students for over a decade.",
    student_b1: "Starter kits from ₹499",
    student_b2: "Bring-your-own-list pickup service",
    student_b3: "Free advice — every counter, every day",
    student_b4: "Development boards · Sensors · Tools",
    student_cta: "Visit the Shop",
    student_img: "HOBBY KITS · STUDENTS",

    stats_label: "BY THE NUMBERS",
    stats_title: "Thirty years on SP Road.",

    audience_label: "WHO WE SERVE",
    audience_title: "Two counters. One philosophy.",
    audience_lede: "Whether you're sourcing for a production line or your final-year project — we treat the question with the same care.",
    industry_tag: "INDUSTRY",
    industry_h: "For manufacturers, integrators, and EMS shops.",
    industry_l1: "MIN ORDER", industry_l1v: "—",
    industry_l2: "TERMS",    industry_l2v: "By arrangement",
    industry_l3: "INVOICING",industry_l3v: "GST · B2B",
    student_tag: "STUDENTS",
    student_h: "For colleges, robotics clubs, and weekend builders.",
    student_l1: "MIN ORDER", student_l1v: "ONE RESISTOR IS FINE",
    student_l2: "KITS FROM", student_l2v: "₹499",
    student_l3: "ADVICE",    student_l3v: "FREE · ALWAYS",

    about_tag: "OUR STORY",
    about_h2: "Thirty years on <em>SP Road</em>.",
    about_sub: "Founded in 1994 by Mr. Kiran Kumar. Still run by him. Still on the same counter.",
    about_p1: "<strong>Mr. Kiran Kumar</strong> started on SP Road in 1994 as a retail counter for passive components and ICs. A year later, word had spread to the industrial belt — manufacturing units and government organisations started placing bulk orders, and a small shop became a trusted procurement partner across Karnataka.",
    about_p2: "Established as Aakash Electronics in 1994, the shop grew quickly. Clients like <strong>L&amp;T, BEL,</strong> and <strong>Indian Railways</strong> became regulars. The range of customers expanded, but the philosophy never changed: stock the right parts, charge a fair price, and treat every question — whether for a thousand-unit order or a single resistor — with the same care.",
    about_p3: "Through the 2000s, as Bengaluru's infrastructure expanded, Aakash added a full range of wires and cables for contractors, integrators, and industrial electricians. Then came engineering students — and the radio assembly kit became one of the top-selling educational products in the region.",
    about_p4: "Today, over thirty years later, Mr. Kiran Kumar still runs the shop from the same SP Road counter. Components across every category, sourced right. Honest pricing. And the same willingness to explain a datasheet as many times as it takes.",
    about_founder_name: "Mr. Kiran Kumar",
    about_founder_role: "Founder & Owner · Est. 1994",
    about_founder_q: "Stock the right parts, charge a fair price, and take every question seriously — that has been our philosophy from day one.",
    about_milestones_h: "Milestones",
    vtl_1994_b: "Founded on SP Road",
    vtl_1994_p: "Mr. Kiran Kumar opens a retail counter — passive components, ICs, and a customer-first approach from the very first day.",
    vtl_1995_b: "Industrial Supply Begins",
    vtl_1995_p: "Officially established as Aakash Electronics. First B2B clients — L&T, BEL, Indian Railways — begin placing bulk orders.",
    vtl_2000_b: "Wires & Cables Division",
    vtl_2000_p: "Expanded into wires and cables to serve the growing demand from infrastructure projects and electrical contractors across Karnataka.",
    vtl_2010_b: "Education & Hobby Kits",
    vtl_2010_p: "Launched curated kits for engineering students. Radio assembly kits became bestsellers — a generation of students built their first circuits here.",
    vtl_today_yr: "Today",
    vtl_today_b: "30+ Years & Going Strong",
    vtl_today_p: "Components across twelve categories — transistors, ICs, capacitors, connectors, sensors, dev boards, and more. Still run by Mr. Kiran Kumar. Still on SP Road. Still answering every question.",

    contact_tag: "GET IN TOUCH",
    contact_h2: 'Come visit us on <span class="r">SP Road</span>.',
    contact_sub: "We answer the phone. We reply to email. The counter is open six days a week.",
    contact_visit_h: "VISIT THE SHOP",
    contact_visit_big: "<span>SP Road, </span><em>Bengaluru</em>",
    contact_addr_k: "ADDRESS",
    contact_addr_v: "#84/4, 1st Floor, N.G.M Plaza,<br>S.P Road, Bengaluru – 560002",
    contact_metro_k: "METRO",
    contact_metro_v: "KR Market (Green Line) — 10 min walk",
    contact_bus_k: "BUS",
    contact_bus_v: "Town Hall bus stop — 5 min walk",
    contact_park_k: "PARKING",
    contact_park_v: "On-street · 2-wheeler easier",
    hours_h: "OPENING HOURS",
    hours_mon: "Monday", hours_tue: "Tuesday", hours_wed: "Wednesday",
    hours_thu: "Thursday", hours_fri: "Friday", hours_sat: "Saturday",
    hours_sun: "Sunday", hours_open: "10:00 — 20:00", hours_closed: "Closed",
    contact_reach_h: "REACH OUT",
    contact_reach_big: "<span>We're a </span><em>phone call</em><span> away.</span>",
    contact_phone_k: "PHONE",
    contact_wa_k: "WHATSAPP",
    contact_wa_cta: "Chat on WhatsApp",
    contact_email_k: "EMAIL",

    footer_tag: "Electronic components for industry, classrooms, and curious minds.",
    footer_visit_h: "VISIT",
    footer_company_h: "COMPANY",
    footer_legal_h: "LEGAL",
    footer_our_story: "Our Story",
    footer_contact: "Contact Us",
    footer_terms: "Terms & Conditions",
    footer_privacy: "Privacy Policy",
    footer_copy: "© 2026 AAKASH ELECTRONICS · BENGALURU · EST. 1994",
    footer_addr1: "#84/4, 1st Floor, N.G.M Plaza",
    footer_addr2: "S.P Road, Bengaluru – 560002",
    footer_hours: "Mon–Sat · 10:00–20:00"
  },

  hi: {
    util_open: "खुला सोम–शनि · 10:00–20:00",
    util_addr: "एस.पी. रोड, बेंगलुरु",

    nav_about: "हमारे बारे में",
    nav_contact: "संपर्क",
    nav_visit: "दुकान आएं",

    hero_eyebrow: "स्था. 1994 · बेंगलुरु",
    hero_h1: '<em class="accent">उद्योग</em>, शिक्षा और<br>जिज्ञासु मनों के लिए इलेक्ट्रॉनिक कंपोनेंट्स।',
    hero_lede: "आकाश इलेक्ट्रॉनिक्स — एस.पी. रोड पर 30 साल पुरानी सप्लाई हाउस। औद्योगिक थोक ऑर्डर से लेकर छात्रों की हॉबी किट तक — हर वो चीज़ जो सर्किट को जिंदा करती है।",
    hero_cta1: "संपर्क करें",
    hero_cta2: "हमारी कहानी",
    hero_trust_label: "विश्वसनीय",

    cat_label: "हम क्या रखते हैं",
    cat_title_a: "बारह श्रेणियाँ, ",
    cat_title_em: "हर ज़रूरी कंपोनेंट",
    cat_title_b: "।",
    cat_lede: "ट्रांज़िस्टर, IC, कैपेसिटर, रेसिस्टर, कनेक्टर, केबल, सेंसर, डेव बोर्ड, LED, PCB, औज़ार और पावर — सब एस.पी. रोड के एक काउंटर पर।",
    cat: {
      passive:     { name: "रेसिस्टर और पैसिव",    meta: "कार्बन फिल्म · मेटल फिल्म · पोटेंशियोमीटर", count: "1,200+ SKU" },
      transistors: { name: "ट्रांज़िस्टर",          meta: "BC · A/B/C/D/K/R सीरीज़ · 500+ पार्ट नंबर",  count: "3,000+ SKU" },
      ics:         { name: "IC और ऑडियो मॉड्यूल",   meta: "TDA · LA · STK · AN · UM · UPC · TA सीरीज़", count: "1,800+ SKU" },
      capacitors:  { name: "कैपेसिटर",              meta: "सिरेमिक 2pF–330K · इलेक्ट्रोलाइटिक · पॉलीएस्टर", count: "2,000+ SKU" },
      connectors:  { name: "कनेक्टर और ऑडियो",      meta: "RCA · XLR · BNC · USB · HDMI · DIN · बनाना", count: "640+ SKU"   },
      leds:        { name: "LED और स्विच",           meta: "5mm · 3mm · कैंडी · टैक्ट 6×6 · 12×12 · रॉकर", count: "280+ SKU" },
      wires:       { name: "केबल और तार",            meta: "DC तार · पैच कॉर्ड · HDMI · USB · शील्डेड", count: "320+ SKU"   },
      sensors:     { name: "सेंसर और मॉड्यूल",       meta: "PIR · गैस MQ2/5/135 · तापमान · RFID · RF 433MHz", count: "640+ SKU" },
      kits:        { name: "डेव बोर्ड और किट",       meta: "Arduino · 8051 · AVR · PIC · ESP32 · Raspberry Pi", count: "180+ SKU" },
      pcbs:        { name: "PCB और प्रोटोटाइपिंग",   meta: "परफबोर्ड · ब्रेडबोर्ड · सिंगल/डबल साइड",    count: "210+ SKU"   },
      tools:       { name: "औज़ार और सोल्डरिंग",    meta: "Soldron आयरन · सोल्डर वायर · प्लायर · कटर",  count: "490+ SKU"   },
      power:       { name: "पावर और अडैप्टर",        meta: "SMPS · लैपटॉप अडैप्टर · 5V–20V · रेगुलेटर", count: "880+ SKU"   }
    },

    bulk_eyebrow: "थोक और B2B",
    bulk_title: "वीकेंड तक बड़ा ऑर्डर चाहिए?",
    bulk_p: "हम कर्नाटक भर के निर्माण इकाइयों, ऑटोमेशन इंटीग्रेटर्स और सरकारी संगठनों को सप्लाई करते हैं। थोक ऑर्डर और BOM सोर्सिंग के लिए हमारे ट्रेड डेस्क से संपर्क करें।",
    bulk_b1: "थोक ऑर्डर पर वॉल्यूम मूल्य",
    bulk_b2: "GST बिलिंग · नकद, UPI और NEFT स्वीकृत",
    bulk_b3: "L&T, BEL, Indian Railways और अधिक को सेवा",
    bulk_b4: "बुनियादी ढांचा परियोजनाओं के लिए तार और केबल",
    bulk_cta: "कोटेशन माँगें",
    bulk_img: "थोक ऑर्डर · B2B",

    student_eyebrow: "छात्रों और मेकर्स के लिए",
    student_title: "इस वीकेंड कुछ बनाइए।",
    student_p: "प्रथम वर्ष इलेक्ट्रॉनिक्स, रोबोटिक्स क्लब और शौकीनों के लिए चुनी हुई किट। हमारी रेडियो असेंबली किट एक दशक से इंजीनियरिंग छात्रों में सबसे ज़्यादा बिकती है।",
    student_b1: "स्टार्टर किट ₹499 से",
    student_b2: "अपनी सूची लाएँ — पिकअप सेवा",
    student_b3: "मुफ्त सलाह — हर काउंटर, हर दिन",
    student_b4: "डेवलपमेंट बोर्ड · सेंसर · औज़ार",
    student_cta: "दुकान आएं",
    student_img: "हॉबी किट · छात्र",

    stats_label: "आँकड़ों में",
    stats_title: "एस.पी. रोड पर तीस साल।",

    audience_label: "हमारे ग्राहक",
    audience_title: "दो काउंटर। एक सोच।",
    audience_lede: "चाहे आप उत्पादन लाइन के लिए सोर्सिंग कर रहे हों या अंतिम-वर्ष प्रोजेक्ट के लिए — हम हर सवाल को बराबर ध्यान देते हैं।",
    industry_tag: "उद्योग",
    industry_h: "निर्माताओं, इंटीग्रेटर्स और EMS शॉप्स के लिए।",
    industry_l1: "न्यूनतम ऑर्डर", industry_l1v: "—",
    industry_l2: "शर्तें",         industry_l2v: "व्यवस्था अनुसार",
    industry_l3: "बिलिंग",         industry_l3v: "GST · B2B",
    student_tag: "छात्र",
    student_h: "कॉलेज, रोबोटिक्स क्लब और वीकेंड बिल्डर्स के लिए।",
    student_l1: "न्यूनतम ऑर्डर", student_l1v: "एक रेसिस्टर भी ठीक",
    student_l2: "किट से शुरू",    student_l2v: "₹499",
    student_l3: "सलाह",           student_l3v: "मुफ्त · हमेशा",

    about_tag: "हमारी कहानी",
    about_h2: "30 साल <em>एस.पी. रोड</em> पर।",
    about_sub: "1994 में श्री किरण कुमार द्वारा स्थापित। आज भी वही चलाते हैं। आज भी उसी काउंटर पर।",
    about_p1: "<strong>श्री किरण कुमार</strong> ने 1994 में एस.पी. रोड पर पैसिव कंपोनेंट्स और IC के लिए एक रिटेल काउंटर शुरू किया। एक साल बाद, बात औद्योगिक क्षेत्र तक पहुँच गई — निर्माण इकाइयों और सरकारी संगठनों ने थोक ऑर्डर देना शुरू किया, और एक छोटी दुकान कर्नाटक भर में एक विश्वसनीय प्रोक्योरमेंट पार्टनर बन गई।",
    about_p2: "1994 में आकाश इलेक्ट्रॉनिक्स के रूप में स्थापित, दुकान तेज़ी से बढ़ी। <strong>L&amp;T, BEL,</strong> और <strong>Indian Railways</strong> जैसे क्लाइंट नियमित हो गए। ग्राहकों की रेंज बढ़ी, लेकिन दर्शन नहीं बदला: सही पुर्जे रखो, उचित दाम लो, और हर सवाल को उतना ही ध्यान दो।",
    about_p3: "2000 के दशक में, जैसे-जैसे बेंगलुरु का बुनियादी ढांचा बढ़ा, आकाश ने कॉन्ट्रैक्टर्स, इंटीग्रेटर्स और औद्योगिक इलेक्ट्रीशियन के लिए तारों और केबलों की पूरी रेंज जोड़ी। फिर इंजीनियरिंग के छात्र आए — और रेडियो असेंबली किट इस क्षेत्र के सबसे ज़्यादा बिकने वाले शैक्षिक उत्पादों में से एक बन गई।",
    about_p4: "आज, तीस से अधिक वर्षों के बाद, श्री किरण कुमार अभी भी उसी एस.पी. रोड काउंटर से दुकान चलाते हैं। हर श्रेणी में घटक, सही तरीके से। ईमानदार मूल्य। और डेटाशीट को जितनी बार ज़रूरत हो उतनी बार समझाने की वही तत्परता।",
    about_founder_name: "श्री किरण कुमार",
    about_founder_role: "संस्थापक और मालिक · स्था. 1994",
    about_founder_q: "सही पुर्जे रखो, उचित दाम लो, और हर सवाल को गंभीरता से लो — यही हमारा दर्शन पहले दिन से रहा है।",
    about_milestones_h: "मील के पत्थर",
    vtl_1994_b: "एस.पी. रोड पर स्थापना",
    vtl_1994_p: "श्री किरण कुमार ने एक रिटेल काउंटर खोला — पैसिव कंपोनेंट्स, IC, और पहले दिन से ग्राहक-पहले का नज़रिया।",
    vtl_1995_b: "औद्योगिक आपूर्ति शुरू",
    vtl_1995_p: "आधिकारिक रूप से आकाश इलेक्ट्रॉनिक्स स्थापित। पहले B2B क्लाइंट — L&T, BEL, Indian Railways — थोक ऑर्डर देने लगे।",
    vtl_2000_b: "तार और केबल विभाग",
    vtl_2000_p: "कर्नाटक भर के बुनियादी ढांचा परियोजनाओं और विद्युत ठेकेदारों की बढ़ती माँग के लिए तारों और केबलों में विस्तार।",
    vtl_2010_b: "शिक्षा और हॉबी किट",
    vtl_2010_p: "इंजीनियरिंग छात्रों के लिए चुनी हुई किट लॉन्च की। रेडियो असेंबली किट बेस्टसेलर बनी — पीढ़ी के छात्रों ने यहीं अपने पहले सर्किट बनाए।",
    vtl_today_yr: "आज",
    vtl_today_b: "30+ साल और मज़बूत",
    vtl_today_p: "बारह श्रेणियों में घटक — ट्रांज़िस्टर, IC, कैपेसिटर, कनेक्टर, सेंसर, डेव बोर्ड और बहुत कुछ। अभी भी श्री किरण कुमार द्वारा। अभी भी एस.पी. रोड पर। अभी भी हर सवाल का जवाब।",

    contact_tag: "संपर्क करें",
    contact_h2: 'हमसे मिलें <span class="r">एस.पी. रोड</span> पर।',
    contact_sub: "हम फोन उठाते हैं। ईमेल का जवाब देते हैं। काउंटर हफ्ते में छह दिन खुला है।",
    contact_visit_h: "दुकान आएं",
    contact_visit_big: "<span>एस.पी. रोड, </span><em>बेंगलुरु</em>",
    contact_addr_k: "पता",
    contact_addr_v: "#84/4, पहली मंज़िल, N.G.M प्लाज़ा,<br>एस.पी. रोड, बेंगलुरु – 560002",
    contact_metro_k: "मेट्रो",
    contact_metro_v: "KR मार्केट (ग्रीन लाइन) — 10 मिनट पैदल",
    contact_bus_k: "बस",
    contact_bus_v: "Town Hall बस स्टॉप — 5 मिनट पैदल",
    contact_park_k: "पार्किंग",
    contact_park_v: "सड़क किनारे · दो-पहिया आसान",
    hours_h: "खुलने का समय",
    hours_mon: "सोमवार", hours_tue: "मंगलवार", hours_wed: "बुधवार",
    hours_thu: "गुरुवार", hours_fri: "शुक्रवार", hours_sat: "शनिवार",
    hours_sun: "रविवार", hours_open: "10:00 — 20:00", hours_closed: "बंद",
    contact_reach_h: "सम्पर्क करें",
    contact_reach_big: "<span>हम एक </span><em>फोन कॉल</em><span> की दूरी पर हैं।</span>",
    contact_phone_k: "फोन",
    contact_wa_k: "व्हाट्सऐप",
    contact_wa_cta: "WhatsApp पर बात करें",
    contact_email_k: "ईमेल",

    footer_tag: "उद्योग, कक्षाओं और जिज्ञासु मनों के लिए कंपोनेंट्स।",
    footer_visit_h: "मिलें",
    footer_company_h: "कंपनी",
    footer_legal_h: "कानूनी",
    footer_our_story: "हमारी कहानी",
    footer_contact: "संपर्क करें",
    footer_terms: "नियम और शर्तें",
    footer_privacy: "गोपनीयता नीति",
    footer_copy: "© 2026 आकाश इलेक्ट्रॉनिक्स · बेंगलुरु · स्था. 1994",
    footer_addr1: "#84/4, पहली मंज़िल, N.G.M प्लाज़ा",
    footer_addr2: "एस.पी. रोड, बेंगलुरु – 560002",
    footer_hours: "सोम–शनि · 10:00–20:00"
  }
};

window.applyLang = function(lang) {
  const dict = window.STRINGS[lang] || window.STRINGS.en;
  document.documentElement.setAttribute('data-lang', lang);
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (dict[key] !== undefined) el.textContent = dict[key];
  });
  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    const key = el.getAttribute('data-i18n-html');
    if (dict[key] !== undefined) el.innerHTML = dict[key];
  });
  window.dispatchEvent(new CustomEvent('langchange', { detail: { lang } }));
};
